haratiapp/urls.py
from django.conf.urls import url
from .views import Index, Logout, SignUp,activate, Clothing, Footwear, WomensWear, BagsAndWallets, Accessories

app_name = 'haratiapp'
urlpatterns = [
    url(r'^$', Index.as_view(), name = 'index'),
    url(r'^logout$', Logout.as_view(), name='logout'),
    url(r'^signup$', SignUp.as_view(), name='signup'),
    url(r'^clothing$', Clothing.as_view(), name='clothing'),
    url(r'^footwear', Footwear.as_view(), name='footwear'),
    url(r'^womenswear', WomensWear.as_view(), name='womenswear'),
    url(r'^bagsandwallets', BagsAndWallets.as_view(), name='bagsandwallets'),
    url(r'^accessories', Accessories.as_view(), name='accessories'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        activate, name='activate'),

]

haraticollection/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('haratiapp.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

haratiapp/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify
from django.shortcuts import reverse

category = (
    ('Clothing','Clothing'), ('FootWear', 'FootWear'), ('Bags&Wallets', 'Bags&Wallets'), ('Accessories', 'Accessories'),
    ('WomenWears','WomenWears')
)


subcategory = (
    ('T-shirt','T-shirt'), ('Casual Shirt', 'Casual Shirt'), ('Half Pants', 'Half Pants'),
    ('Jeans','Jeans'),
    ('Trousers','Trousers'),
    ('Sportswear', 'Sportswear'),
    ('Sweaters', 'Sweaters'),
    ('Boxers', 'Boxers'),
    ('Thermal','Thermal'),
    ('Windcheater','Windcheater')
)


size = (
    ('Double-Extra-Large', 'XXL'),
    ('Extra-Large', 'XL'),
    ('Large', 'L'),
    ('Medium', 'M'),
    ('Small', 'S'),
)
# Create your models here.

quantity = (
    (1, '1'),
    (2, '2'),
    (3,'3'),
    (4,'4'),
    (5,'5'),
    ( 6,'6'),
    (7,'7'),(8,'8'),(9,'9'),(10, '10')
)

color = (
    ('Red','Red'),
    ('Blue', 'Blue'),
    ('Black', 'Black'),
    ('Yellow', 'Yellow'),
    ('White', 'White'),
    ('Green', 'Green')

)

status = (
    (1, 'Yes'),
    (0, 'No')
)

class Time(models.Model):
    created_at = models.DateTimeField(auto_now_add=True, auto_now=False, )
    updated_at = models.DateTimeField(auto_now_add=False, auto_now=True, )
    deleted_at = models.DateTimeField(null=True, blank=True)
    class Meta:
        abstract = True

    def delete(self,*args,**kwargs):
        self.deleted_at = timezone.now()
        super().save()

################################################# NEW CONCEPT ############################################################



class SubCategory(models.Model):
    category=models.CharField(choices=category, max_length=100)
    subcategory=models.CharField(max_length=100)

    def __str__(self):
        return self.subcategory

class Item(Time):
    name = models.CharField(max_length=100)
    description = models.TextField(blank=True,null=True)
    item_number = models.CharField(max_length=25,blank=True,null=True)
    subcategory = models.ForeignKey(SubCategory, on_delete=models.CASCADE, blank=True, null=True)
    size = models.CharField(choices=size, max_length=25,blank=True,null=True)
    color = models.CharField(choices=color, max_length=25,blank=True,null=True)
    price = models.IntegerField(blank=True,null=True)
    status = models.BooleanField(choices=((True,'Publish'),(False,'Dont Publish')), default=False)
    photo = models.ImageField(upload_to='media_cdn', blank=True,null=True)
    slug = models.SlugField(blank=True)
    like = models.ManyToManyField(User, blank = True)
    size_slug = models.SlugField(blank=True)

    def __str__(self):
        return self.name


    def save(self, *args, **kwargs):
        self.slug = slugify(self.subcategory.category)
        self.size_slug = slugify(self.size)
        super(Item, self).save(*args, **kwargs)


    class Meta:
        ordering = ('-id',)

    def get_absoulte_url(self):
        return reverse('haratiapp:detail_category', kwargs={'pk':self.pk})

    def like_count(self):
        return self.like.count()



class Featured(models.Model):
    featured = models.ForeignKey(Item)
    def __str__(self):
        return self.featured.name


class Trending(models.Model):
    trending = models.ForeignKey(Item)
    def __str__(self):
        return self.trending.name


class Latest(models.Model):
    latest = models.ForeignKey(Item)
    def __str__(self):
        return self.latest.name


class Logo(models.Model):
    logo = models.ImageField(upload_to='images')

haratiapp/forms.py
from django import forms
from .models import Item
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class LoginForm(forms.Form):
    loginusername = forms.CharField(
    widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'Enter Email',
        }
    )
    )
    loginpassword = forms.CharField(widget=forms.PasswordInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'Enter Password',
        }
    ))


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Enter your firstname'
            }
        ), required=False, max_length=30, help_text='Optional'
    )
    last_name = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Enter your lastname'
            }
        ), required=False, max_length=30, help_text='Optional'
    )

    email = forms.EmailField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Email address'
            }
        ), required=True, max_length=254, help_text='Required. Inform a valid email address.'
    )
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Enter your username'
            }
        ), required=True, max_length=30, help_text='Required. Inform a valid email username.'
    )

    password1 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Enter your Password'
            }
        ), required=True, max_length=30, help_text='Required. (Min 8 characters)'
    )

    password2 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Confirm your password.'
            }
        ), required=True, max_length=30, help_text='Confirm your password.'
    )


    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2', )



class AddProduct(forms.ModelForm):
   class Meta:
        model = Item
        fields = ['name', 'description',
                  'item_number', 'size', 'color', 'subcategory', 'price',
                  'status']
        widgets = {
            'name': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Enter product name',
                'required': 'True',
                            }),
            'description': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Enter description of your product.',

                            }),
            'item_number': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Enter item number',

            }),
            'size': forms.Select(attrs={
                'class': 'form-control borderline',
                'placeholder': 'Enter Size',


            }),
             'color': forms.Select(attrs={
                 'class': 'form-control',
                 'placeholder': 'Color',

             }),


            'subcategory': forms.Select(attrs={
                'class': 'form-control',
                'placeholder': 'Subcategory',

            }),

            'price': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Enter Price',

            }),

            'status': forms.Select(attrs={
                'class': 'form-control',
              }),
        }

haratiapp/views.py
from django.shortcuts import render, HttpResponse, HttpResponseRedirect, reverse
from django.views import View
from .models import Logo, Item
from .forms import LoginForm, SignUpForm, AddProduct
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.models import User
from django.views.generic import TemplateView, ListView, CreateView
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.core.mail import EmailMessage
from haratiapp.tokens import account_activation_token
from django.utils.encoding import force_bytes, force_text
from django.urls import reverse_lazy

from django.contrib.auth import get_user_model

# Create your views here.

class Index(View):
    def get(self, request):
        logo = Logo.objects.all()[1]
        form = LoginForm()
        rform = SignUpForm()
        user = get_user_model()
        print(user.username)
        return render(request, 'homepage.html', {'obj':logo, 'loginform': form , 'register':rform} )

    def post(self, request):
        form = LoginForm(request.POST)
        register = SignUpForm(request.POST)

        if form.is_valid():
            username = form.cleaned_data['loginusername']
            password = form.cleaned_data['loginpassword']
            user = authenticate(username=username, password=password)


            if user is not None:
                login(self.request, user)
                print('User logged in !!')
                if user.is_superuser:
                    messages.success(self.request, 'Soooooooper USSERRRRRRRRRR !!')
                    return HttpResponseRedirect(reverse('haratiapp:index'))
                else:
                    messages.success(self.request, 'Login Successful !!')
                    return HttpResponseRedirect(reverse('haratiapp:index'))

            else:
                messages.warning(self.request, 'Please check your username and password !!')
                return HttpResponseRedirect(reverse('haratiapp:index'))


        elif register.is_valid():
            user = register.save(commit=False)
            user.is_active = False
            user.save()
            current_site = get_current_site(request)
            subject = 'Activate Your MySite Account'
            message = render_to_string('account_activation_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': account_activation_token.make_token(user),
            })
            to_email = register.cleaned_data.get('email')

            email = EmailMessage(
                subject, message, to=[to_email]

            )
            email.send()
            messages.info(request, 'Email has been sent !!')
            return HttpResponseRedirect(reverse('haratiapp:index'))


        else:
            return HttpResponse('Null')



class Logout(TemplateView):
    def get(self, request):
        logout(request)
        messages.info(request, 'Logged Out !!')
        return HttpResponseRedirect(reverse('haratiapp:index'))


class SignUp(View):
    def get(self, request):
        form = SignUpForm()
        return render(request, 'register.html', {'register':form})

    def post(self, request):
        print("signup post method called")
        form = SignUpForm(request.POST)
        if form.is_valid():
            print('form valid !!')
        return reverse('haratiapp:index')




def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        login(request, user)

        return render(request, 'activate.html')
    else:
        return HttpResponse('Activation link is invalid!')


class Clothing(ListView):
    model = Item
    template_name = 'clothing.html'

    def get_context_data(self, **kwargs):
        context  = super().get_context_data(**kwargs)
        context['active'] = 'clothing'
        return context



class Footwear(ListView):
    model = Item
    template_name = 'footwear.html'

    def get_context_data(self, **kwargs):
        context  = super().get_context_data(**kwargs)
        context['active'] = 'footwear'
        return context


class BagsAndWallets(ListView):
    model = Item
    template_name = 'bagsandwallets.html'

    def get_context_data(self, **kwargs):
        context  = super().get_context_data(**kwargs)
        context['active'] = 'bagsandwallets'
        return context


class WomensWear(ListView):
    model = Item
    template_name = 'womenswears.html'

    def get_context_data(self, **kwargs):
        context  = super().get_context_data(**kwargs)
        context['active'] = 'womenswear'
        return context


class Accessories(ListView):
    model = Item
    template_name = 'accessories.html'

    def get_context_data(self, **kwargs):
        context  = super().get_context_data(**kwargs)
        context['active'] = 'accessories'
        return context





################ ADMIN CREATE/LIST #############################

haratiapp/templates/accessories.html
{% extends 'base.html' %}

{% block content %}
accessories accessories accessories
{% endblock %}

haratiapp/templates/account_activation_email.html
Hi {{ user.first_name }},

Please click on the link below to confirm your registration:
http://{{ domain }}{% url 'haratiapp:activate' uidb64=uid token=token %}

haratiapp/templates/activate.html
    {% extends 'base.html' %}
    {% block content %}
        <div class="container">
            <div class="jumbotron">
                <h1>Account Activated !!</h1>
                <p>Please <a href="{% url 'haratiapp:index' %}">click here</a> to continue. </p>
                <p>Thank You</p>
            </div>
        </div>
    {% endblock %}

haratiapp/templates/bagsandwallets.html
{% extends 'base.html' %}

{% block content %}
     bags&wallets bags&wallets bags&wallets
{% endblock %}

haratiapp/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
{% load static %}

    {% block title %}
        <title>Title</title>
    {% endblock %}
<script src="http://code.jquery.com/jquery-1.11.0.min.js"></script>
<script src="http://code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>


</head>
<body>


    <link rel="stylesheet" href="{% static 'css/homepagestyles.css' %}">
    <script src="{% static 'js/custom.js' %}"></script>
    {% comment %}
    Navbar begins from here
    {% endcomment %}
    <div class="navbarrr" >

        <div class="left">
        <img src="{{ obj.logo.url }}" alt="Nno" style="max-height: 150px; max-width: 150px;">
        </div>
        <div class="center text-center">
            <h3>Harati Collection Center</h3>
            <p>Because quality cannot be compromised...</p>
            <p>We offer what you seek for...</p>
        </div>
        <div class="right" style="display: grid;">
            <iframe src="https://www.zeitverschiebung.net/clock-widget-iframe-v2?language=en&size=small&timezone=Asia%2FKathmandu"
                    width="100%" frameborder="0">
            </iframe>
        </div>
    </div>

    <nav class="navbar navbar-default" style="background-color: #FD7300"role="navigation">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'haratiapp:index' %}">HCC</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li class={% if active == 'clothing' %}"active"{% endif %}>  <a href="{% url 'haratiapp:clothing' %}">Clothing</a></li>
                <li class= {% if active == 'footwear' %} "active" {% endif%}><a href="{% url 'haratiapp:footwear' %}">FootWear</a></li>
                <li class= {% if active == 'bagsandwallets' %} "active" {% endif%}><a href="{% url 'haratiapp:bagsandwallets' %}">Bags & Wallets</a></li>
                <li class= {% if active == 'womenswear' %} "active" {% endif%}><a href="{% url 'haratiapp:womenswear' %}">Womens Wear</a></li>
                <li class= {% if active == 'accessories' %} "active" {% endif%}><a href="{% url 'haratiapp:accessories' %}">Accessories</a></li>
            </ul>



            <ul class="nav navbar-nav navbar-right">

            {% if user.is_authenticated %}
                <li><a href="" style="color: green; font-size: 25px;">Welcome! {{ user.first_name }}</a></li>
            {% else %}

                <!-- Modal -->
                <div class="modal fade" id="loginmodal" tabindex="-1" role="dialog"
                     aria-labelledby="headmodallabel" aria-hidden="true">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="headmodallabel">Login</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                <form class="login-form" method="post">
                                    {% csrf_token %}
                                    <div class="form-group">
                                        <label for="loginemail">Email address</label>
                                        <div id="loginemail">{{ loginform.loginusername }}</div>
                                    </div>
                                    <div class="form-group">
                                        <label for="loginpassword">Password</label>
                                        <div id="loginpassword">{{ loginform.loginpassword }}</div>
                                        <small id="emailHelp" class="form-text text-muted">We'll never share your email
                                            with anyone
                                            else.
                                        </small>
                                    </div>
                                    <button type="submit" class="btn btn-success" style="width: 100%">Login</button>
                                </form>

                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                            </div>
                        </div>
                    </div>
                </div>


                <!-- Modal -->
                <div class="modal fade" id="registermodal" tabindex="-1" role="dialog"
                     aria-labelledby="headregistermodal" aria-hidden="true">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="headregistermodal">Register</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                <form class="register-form" method="post" id="register" action="">
                                    {% csrf_token %}

                                    <div class="form-group">
                                        <label for="registeremail">Firstname:</label>
                                        <div id="registeremail">{{ register.first_name }}</div>
                                    </div>

                                    <div class="form-group">
                                        <label for="registeremail">LastName:</label>
                                        <div id="registeremail">{{ register.last_name }}</div>
                                    </div>

                                    <div class="form-group">
                                        <label for="registerusername">Username:</label>
                                        <div id="registerusername">{{ register.username }}</div>
                                    </div>
                                    <div class="form-group">
                                        <label for="registerpassword">Password:</label>
                                        <div id="registerpassword">{{ register.password1 }}</div>

                                    </div>

                                    <div class="form-group">
                                        <label for="registerrepassword">Re-Enter Password:</label>
                                        <div id="registerrepassword">{{ register.password2 }}</div>
                                    </div>

                                    <div class="form-group">
                                        <label for="registeremail">Email:</label>
                                        <div id="registeremail">{{ register.email }}</div>
                                    </div>



                                    <button type="submit" class="btn btn-primary" style="width: 100%">Register</button>
                                </form>

                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                            </div>
                        </div>
                    </div>
                </div>
                {% endif %}

                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Drop Data <b class="caret"></b></a>
                    <ul class="dropdown-menu">

                        {% if user.is_authenticated %}

                        <li><a href="{% url 'haratiapp:logout' %}"><i class="fa fa-user" style="padding: 0 10px;"></i>Logout</a></li>
                        <li class="divider"></li>

                        {% else %}
                        <li data-toggle="modal" data-target="#loginmodal"><a href="#"><i class="fa fa-user" style="padding: 0 10px;"></i>Login</a></li>
                        <li class="divider"></li>


                        <li data-toggle="modal" data-target="#registermodal"><a href="#"><i class="fa fa-user-plus" style="padding: 0 10px;"></i>Register</a></li>
                        <li class="divider"></li>

                        {% endif %}

                        <li><a href=""><i class="fa fa-phone" aria-hidden="true" style="padding: 0 10px;"></i>Contact Us</a>
                        </li>
                        <li class="divider"></li>
                        <li><a href="#"><i class="fa fa-info-circle" style="padding: 0 10px;"></i>About</a></li>
                    </ul>
                </li>
            </ul>

            <div class="col-sm-3 col-md-3" style="float: left">
                <form class="navbar-form" role="search">
                    <div class="input-group">
                        <input type="text" class="form-control" placeholder="Search" name="q">
                        <div class="input-group-btn">
                            <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div><!-- /.navbar-collapse -->
    </nav>

    {% if messages %}

    {% for message in messages %}

        <div class="alert alert-{{ message.tags }} text-center" role="alert">
  {{ message }}
</div>

    {% endfor %}

    {% endif %}


    {% comment %}
    Navbar Ends from here
    {% endcomment %}






{% block content %}
{% endblock %}


</body>
</html>

haratiapp/templates/clothing.html
{% extends 'base.html' %}

{% block content %}
    Clothing Clothing Clothing
{% endblock %}

haratiapp/templates/footwear.html
{% extends 'base.html' %}

{% block content %}
    Footwear Footwear Footwear
{% endblock %}

haratiapp/templates/login.html
{% extends 'base.html' %}

<div class="content">

</div>

haratiapp/templates/register.html
<form class="register-form" method="post" id="register" action="{% url 'haratiapp:signup' %}">
{% csrf_token %}

<div class="form-group">
<label for="registeremail">Enter Firstname</label>
<div id="registeremail">{{ register.first_name }}</div>
</div>

<div class="form-group">
<label for="registeremail">Enter LastName</label>
<div id="registeremail">{{ register.last_name }}</div>
</div>

<div class="form-group">
<label for="registerusername">Enter Username:</label>
<div id="registerusername">{{ register.username }}</div>
</div>
<div class="form-group">
<label for="registerpassword">Enter Password</label>
<div id="registerpassword">{{ register.password1 }}</div>

</div>

<div class="form-group">
<label for="registerrepassword">Re-Enter Password</label>
<div id="registerrepassword">{{ register.password2 }}</div>
</div>

<div class="form-group">
<label for="registeremail">Enter Email</label>
<div id="registeremail">{{ register.email }}</div>
</div>
<button type="submit" class="btn btn-primary" style="width: 100%">Register</button>
</form>

haratiapp/templates/test.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'css/adminstyles.css' %}">
</head>
<body>
{% load thumbnail %}

{% for o in obj %}

    <img src="{{ o.image.url }}" alt="">

{% endfor %}

</body>
</html>

haratiapp/templates/womenswears.html
{% extends 'base.html' %}

{% block content %}
 womens's wearswomens's wearswomens's wears


{% endblock %}